name: user_repository
description: User Repository
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dev_dependencies:
  build_runner: ^2.4.11
  isar_generator: ^3.1.0+1
  very_good_analysis: ^6.0.0

dependencies:
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  shared_preferences: ^2.3.2
