name: practicame_app
description: Practica.me
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  logger: ^2.4.0
  user_repository:
    path: packages/user_repository
  carousel_slider: ^5.0.0
  audioplayers: ^6.1.0
  shared_preferences: ^2.3.2

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/pictograms/
    - assets/sounds/
    - assets/visual_helps/
    - assets/eps/
    - assets/brand/
